server:
  port: 8080

swagger:
  generateDocs: true
  swaggerServerOn: true

services:
  example: /services/apigateway

serviceDiscovery:
  # servers of etcd cluster this service used to visit
  etcdServers:
    - 127.0.0.1:2379