// Code generated by protoc-gen-go. DO NOT EDIT.
// source: production.proto

package production

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddProductionRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ValueDate            int64    `protobuf:"varint,4,opt,name=valueDate,proto3" json:"valueDate,omitempty"`
	DueDate              int64    `protobuf:"varint,5,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	AnnualRate           int64    `protobuf:"varint,6,opt,name=annualRate,proto3" json:"annualRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductionRequest) Reset()         { *m = AddProductionRequest{} }
func (m *AddProductionRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductionRequest) ProtoMessage()    {}
func (*AddProductionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_production_c047d4dc0b0497a3, []int{0}
}
func (m *AddProductionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductionRequest.Unmarshal(m, b)
}
func (m *AddProductionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductionRequest.Marshal(b, m, deterministic)
}
func (dst *AddProductionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductionRequest.Merge(dst, src)
}
func (m *AddProductionRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductionRequest.Size(m)
}
func (m *AddProductionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductionRequest proto.InternalMessageInfo

func (m *AddProductionRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddProductionRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AddProductionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddProductionRequest) GetValueDate() int64 {
	if m != nil {
		return m.ValueDate
	}
	return 0
}

func (m *AddProductionRequest) GetDueDate() int64 {
	if m != nil {
		return m.DueDate
	}
	return 0
}

func (m *AddProductionRequest) GetAnnualRate() int64 {
	if m != nil {
		return m.AnnualRate
	}
	return 0
}

type AddProductionResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductionResponse) Reset()         { *m = AddProductionResponse{} }
func (m *AddProductionResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductionResponse) ProtoMessage()    {}
func (*AddProductionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_production_c047d4dc0b0497a3, []int{1}
}
func (m *AddProductionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductionResponse.Unmarshal(m, b)
}
func (m *AddProductionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductionResponse.Marshal(b, m, deterministic)
}
func (dst *AddProductionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductionResponse.Merge(dst, src)
}
func (m *AddProductionResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductionResponse.Size(m)
}
func (m *AddProductionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductionResponse proto.InternalMessageInfo

func (m *AddProductionResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddProductionResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetAllProductionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductionRequest) Reset()         { *m = GetAllProductionRequest{} }
func (m *GetAllProductionRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProductionRequest) ProtoMessage()    {}
func (*GetAllProductionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_production_c047d4dc0b0497a3, []int{2}
}
func (m *GetAllProductionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductionRequest.Unmarshal(m, b)
}
func (m *GetAllProductionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductionRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllProductionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductionRequest.Merge(dst, src)
}
func (m *GetAllProductionRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProductionRequest.Size(m)
}
func (m *GetAllProductionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductionRequest proto.InternalMessageInfo

type GetAllProductionResponse struct {
	Status               int64         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Production           []*Production `protobuf:"bytes,2,rep,name=production,proto3" json:"production,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAllProductionResponse) Reset()         { *m = GetAllProductionResponse{} }
func (m *GetAllProductionResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllProductionResponse) ProtoMessage()    {}
func (*GetAllProductionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_production_c047d4dc0b0497a3, []int{3}
}
func (m *GetAllProductionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductionResponse.Unmarshal(m, b)
}
func (m *GetAllProductionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductionResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllProductionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductionResponse.Merge(dst, src)
}
func (m *GetAllProductionResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllProductionResponse.Size(m)
}
func (m *GetAllProductionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductionResponse proto.InternalMessageInfo

func (m *GetAllProductionResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetAllProductionResponse) GetProduction() []*Production {
	if m != nil {
		return m.Production
	}
	return nil
}

type Production struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ValueDate            int64    `protobuf:"varint,4,opt,name=valueDate,proto3" json:"valueDate,omitempty"`
	DueDate              int64    `protobuf:"varint,5,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	AnnualRate           int64    `protobuf:"varint,6,opt,name=annualRate,proto3" json:"annualRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Production) Reset()         { *m = Production{} }
func (m *Production) String() string { return proto.CompactTextString(m) }
func (*Production) ProtoMessage()    {}
func (*Production) Descriptor() ([]byte, []int) {
	return fileDescriptor_production_c047d4dc0b0497a3, []int{4}
}
func (m *Production) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Production.Unmarshal(m, b)
}
func (m *Production) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Production.Marshal(b, m, deterministic)
}
func (dst *Production) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Production.Merge(dst, src)
}
func (m *Production) XXX_Size() int {
	return xxx_messageInfo_Production.Size(m)
}
func (m *Production) XXX_DiscardUnknown() {
	xxx_messageInfo_Production.DiscardUnknown(m)
}

var xxx_messageInfo_Production proto.InternalMessageInfo

func (m *Production) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Production) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Production) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Production) GetValueDate() int64 {
	if m != nil {
		return m.ValueDate
	}
	return 0
}

func (m *Production) GetDueDate() int64 {
	if m != nil {
		return m.DueDate
	}
	return 0
}

func (m *Production) GetAnnualRate() int64 {
	if m != nil {
		return m.AnnualRate
	}
	return 0
}

func init() {
	proto.RegisterType((*AddProductionRequest)(nil), "production.AddProductionRequest")
	proto.RegisterType((*AddProductionResponse)(nil), "production.AddProductionResponse")
	proto.RegisterType((*GetAllProductionRequest)(nil), "production.GetAllProductionRequest")
	proto.RegisterType((*GetAllProductionResponse)(nil), "production.GetAllProductionResponse")
	proto.RegisterType((*Production)(nil), "production.Production")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductionServiceClient is the client API for ProductionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductionServiceClient interface {
	AddProduction(ctx context.Context, in *AddProductionRequest, opts ...grpc.CallOption) (*AddProductionResponse, error)
	GetAllProduction(ctx context.Context, in *GetAllProductionRequest, opts ...grpc.CallOption) (*GetAllProductionResponse, error)
}

type productionServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductionServiceClient(cc *grpc.ClientConn) ProductionServiceClient {
	return &productionServiceClient{cc}
}

func (c *productionServiceClient) AddProduction(ctx context.Context, in *AddProductionRequest, opts ...grpc.CallOption) (*AddProductionResponse, error) {
	out := new(AddProductionResponse)
	err := c.cc.Invoke(ctx, "/production.ProductionService/AddProduction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionServiceClient) GetAllProduction(ctx context.Context, in *GetAllProductionRequest, opts ...grpc.CallOption) (*GetAllProductionResponse, error) {
	out := new(GetAllProductionResponse)
	err := c.cc.Invoke(ctx, "/production.ProductionService/GetAllProduction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductionServiceServer is the server API for ProductionService service.
type ProductionServiceServer interface {
	AddProduction(context.Context, *AddProductionRequest) (*AddProductionResponse, error)
	GetAllProduction(context.Context, *GetAllProductionRequest) (*GetAllProductionResponse, error)
}

func RegisterProductionServiceServer(s *grpc.Server, srv ProductionServiceServer) {
	s.RegisterService(&_ProductionService_serviceDesc, srv)
}

func _ProductionService_AddProduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServiceServer).AddProduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production.ProductionService/AddProduction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServiceServer).AddProduction(ctx, req.(*AddProductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionService_GetAllProduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServiceServer).GetAllProduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production.ProductionService/GetAllProduction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServiceServer).GetAllProduction(ctx, req.(*GetAllProductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "production.ProductionService",
	HandlerType: (*ProductionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProduction",
			Handler:    _ProductionService_AddProduction_Handler,
		},
		{
			MethodName: "GetAllProduction",
			Handler:    _ProductionService_GetAllProduction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "production.proto",
}

func init() { proto.RegisterFile("production.proto", fileDescriptor_production_c047d4dc0b0497a3) }

var fileDescriptor_production_c047d4dc0b0497a3 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xcd, 0x3a, 0x27, 0x7b, 0x22, 0xd4, 0x87, 0xce, 0x38, 0x44, 0x6a, 0xf5, 0xd0, 0xd3,
	0x0e, 0x13, 0xbc, 0x17, 0x04, 0xaf, 0x52, 0xc1, 0xab, 0xc4, 0xf6, 0x21, 0x93, 0xae, 0xa9, 0x4d,
	0x3a, 0xf0, 0xbf, 0xf1, 0xec, 0xdf, 0xe2, 0x1f, 0x25, 0x49, 0x3b, 0x1b, 0x37, 0x9d, 0x57, 0x6f,
	0x5f, 0x7e, 0x5f, 0xda, 0x7c, 0xf9, 0xf2, 0xc0, 0x2f, 0x2b, 0x99, 0xd5, 0xa9, 0x9e, 0xc9, 0x62,
	0x52, 0x56, 0x52, 0x4b, 0x84, 0x8e, 0x84, 0xef, 0x0c, 0x0e, 0xe2, 0x2c, 0xbb, 0xfd, 0x22, 0x09,
	0xbd, 0xd4, 0xa4, 0x34, 0x22, 0xf4, 0xf5, 0x6b, 0x49, 0x9c, 0x05, 0x2c, 0x1a, 0x26, 0x56, 0x1b,
	0x96, 0xca, 0x8c, 0x78, 0xaf, 0x61, 0x46, 0x1b, 0x56, 0x88, 0x39, 0x71, 0xaf, 0x61, 0x46, 0xe3,
	0x09, 0x0c, 0x17, 0x22, 0xaf, 0xe9, 0x5a, 0x68, 0xe2, 0xfd, 0x80, 0x45, 0x5e, 0xd2, 0x01, 0xe4,
	0xb0, 0x93, 0xb5, 0xde, 0xb6, 0xf5, 0x96, 0x4b, 0x3c, 0x05, 0x10, 0x45, 0x51, 0x8b, 0x3c, 0x31,
	0xe6, 0xc0, 0x9a, 0x0e, 0x09, 0x63, 0x38, 0x5c, 0xc9, 0xaa, 0x4a, 0x59, 0x28, 0xc2, 0x11, 0x0c,
	0x94, 0x16, 0xba, 0x56, 0x36, 0xae, 0x97, 0xb4, 0x2b, 0xf4, 0xc1, 0x9b, 0xab, 0xa7, 0x36, 0xaf,
	0x91, 0xe1, 0x31, 0x1c, 0xdd, 0x90, 0x8e, 0xf3, 0x7c, 0xed, 0xc6, 0xe1, 0x33, 0xf0, 0x75, 0xeb,
	0x8f, 0x03, 0xae, 0xc0, 0x29, 0x93, 0xf7, 0x02, 0x2f, 0xda, 0x9d, 0x8e, 0x26, 0x4e, 0xe3, 0xce,
	0xbf, 0xdc, 0xda, 0xdf, 0x18, 0x40, 0x67, 0xfd, 0xc7, 0xb2, 0xa7, 0x1f, 0x0c, 0xf6, 0xbb, 0x88,
	0x77, 0x54, 0x2d, 0x66, 0x29, 0xe1, 0x3d, 0xec, 0x7d, 0x7b, 0x02, 0x0c, 0xdc, 0xdb, 0xfe, 0x34,
	0x49, 0xe3, 0xb3, 0x0d, 0x3b, 0x9a, 0x7a, 0xc3, 0x2d, 0x7c, 0x00, 0x7f, 0xb5, 0x7c, 0x3c, 0x77,
	0x3f, 0xfc, 0xe5, 0xd5, 0xc6, 0x17, 0x9b, 0x37, 0x2d, 0x0f, 0x78, 0x1c, 0xd8, 0xd9, 0xbf, 0xfc,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0x92, 0x1f, 0x3a, 0x78, 0x0f, 0x03, 0x00, 0x00,
}
